# config/internal_users.yml
# 비밀번호: P@ssw0rd123! 의 BCrypt 해시

_meta:
  type: "internalusers"
  config_version: 2


admin:
  # 여기에 1단계에서 복사한 해시를 붙여넣습니다. (작은따옴표로 감싸야 함) MyNewP@ssw0rd24!
  hash: '$2y$12$Si2wWQ7Vool46hHH5rJXaua7hslCgv9iul1yXWaNweltcful7EHr.'
  opendistro_security_roles:
    - "all_access" # 관리자 역할을 명시적으로 추가

logs_writer:
  hash: "$2a$12$6q87E6dFv8NfH1hM8E/9.uX0rQ1M.v/QWwYw7X/J8zTzR.yYxHqS." 
  opendistro_security_roles: []
user_tenantA:
  hash: "$2a$12$6q87E6dFv8NfH1hM8E/9.uX0rQ1M.v/QWwYw7X/J8zTzR.yYxHqS."
  opendistro_security_roles: []
user_tenantB:
  hash: "$2a$12$6q87E6dFv8NfH1hM8E/9.uX0rQ1M.v/QWwYw7X/J8zTzR.yYxHqS."
  opendistro_security_roles: []
