# internal_users_reset.yml (로컬 파일)
_meta:
  type: "internalusers"
  config_version: 2

admin:
  # 여기에 1단계에서 복사한 해시를 붙여넣습니다. (작은따옴표로 감싸야 함) MyNewP@ssw0rd24!
  hash: '$2y$12$Si2wWQ7Vool46hHH5rJXaua7hslCgv9iul1yXWaNweltcful7EHr.'
  opendistro_security_roles:
    - "all_access" # 관리자 역할을 명시적으로 추가
