# config/roles_mapping.yml

_meta:
  type: "rolesmapping"
  config_version: 2

logs_writer_role:
  users:
    - logs_writer
tenant_a_analyst_role:
  users:
    - user_tenantA
tenant_b_analyst_role:
  users:
    - user_tenantB
